FROM docker.io/jupyterhub/jupyterhub@sha256:97215fe76d3fce1261b211d67fc7cdb9c6b21369140400bb7bb308c03ba0590e

RUN pip install --no-cache-dir \
    jupyterlab \
    certifi \
    jupyterhub-remote-user-authenticator \
    dockerspawner \
    notebook \
    ipykernel

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY caddy-ca.crt /tmp/caddy-ca.crt
RUN cat /tmp/caddy-ca.crt >> /srv/venv/lib/python3.12/site-packages/certifi/cacert.pem && \
    cat /tmp/caddy-ca.crt >> /etc/ssl/certs/ca-certificates.crt && \
    update-ca-certificates

RUN mkdir -p /home/jovyan/notebooks && \
    groupadd --gid 10001 jupyterhub && \
    useradd --uid 10001 --gid 10001 --home-dir /home/jovyan --no-create-home jupyterhub && \
    mkdir -p /srv/jupyterhub && \
    chown -R jupyterhub:jupyterhub /home/jovyan /srv/jupyterhub && \
    chmod 755 /home/jovyan && \
    chmod 700 /home/jovyan/notebooks

USER jupyterhub
